spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/palliser?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USER:palliser}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
